default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db_dev

test:
  <<: *default
  database: db_testing

production:
  <<: *default
  database: db_release
